config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("", include("rewards.urls", namespace="rewards")),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    path("rewards/", include("rewards.urls", namespace="rewards")),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("holistiplan.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

rewards/urls.py
from django.urls import path

from . import views

app_name = "rewards"
urlpatterns = [
    path("", views.RewardsListView.as_view(), name="list"),
    path("claim/", views.RewardsClaimView.as_view(), name="claim"),
    path("bonus/", views.RewardsBonusView.as_view(), name="bonus"),
]

rewards/models.py
from django.conf import settings
from django.db import models


class Reward(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    point_value = models.DecimalField(max_digits=9, decimal_places=2, default=1.00)

    def __str__(self) -> str:
        return self.name


class UserPoints(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    points_granted = models.DecimalField(max_digits=9, decimal_places=2, default=10.00)
    points_spent = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)

rewards/views.py
from decimal import Decimal
from typing import Any

from django.contrib import messages
from django.core.exceptions import SuspiciousOperation
from django.db.models import Sum
from django.http import JsonResponse
from django.shortcuts import redirect
from django.urls import reverse
from django.views import generic

from rewards.models import Reward, UserPoints

SESSION_KEY_POINTS_GRANTED = "points_granted"
SESSION_KEY_POINTS_SPENT = "points_spent"
GUEST_POINTS = 10
ADD_POINTS_BONUS = 5


def get_points(user, session):
    if user.is_authenticated:
        user_points, _ = UserPoints.objects.get_or_create(user=user)
        return user_points.points_granted, user_points.points_spent
    else:
        return Decimal(session.get(SESSION_KEY_POINTS_GRANTED, default=GUEST_POINTS)), Decimal(
            session.get(SESSION_KEY_POINTS_SPENT, default="0")
        )


class RewardsListView(generic.ListView):
    template_name = "rewards/list.html"
    context_object_name = "rewards"

    def get_queryset(self):
        return Reward.objects.all()

    def get_context_data(self, **kwargs: object) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        points_avail, points_spent = get_points(self.request.user, self.request.session)
        context["redeemable_points"] = points_avail - points_spent
        return context


class RewardsClaimView(generic.View):
    template_name = "rewards/claim.html"

    def post(self, request):
        claimed_reward_ids = request.POST.getlist("rewardId")
        claimed_rewards = Reward.objects.filter(id__in=claimed_reward_ids)
        point_sum = claimed_rewards.aggregate(Sum("point_value")).get("point_value__sum", 0.00)
        points_granted, points_spent = get_points(request.user, request.session)

        if point_sum <= points_granted - points_spent:
            messages.add_message(
                request,
                messages.INFO,
                f"You successfully claimed the following rewards: {', '.join([r.name for r in claimed_rewards])}",
            )

            if request.user.is_authenticated:
                user_points, _ = UserPoints.objects.get_or_create(user=request.user)
                user_points.points_spent += point_sum
                user_points.save()
            else:
                request.session[SESSION_KEY_POINTS_SPENT] = str(point_sum + points_spent)

            return redirect(reverse("rewards:list"))

        else:
            raise SuspiciousOperation("Invalid request; Exceeded available points")


class RewardsBonusView(generic.View):
    def post(self, request):
        num_points = Decimal(request.POST.get("numPoints", ADD_POINTS_BONUS))
        if request.user.is_authenticated:
            user_points, _ = UserPoints.objects.get_or_create(user=request.user)
            user_points.points_granted += num_points
            user_points.save()
            points_granted = user_points.points_granted
        else:
            points_granted = num_points + Decimal(request.session.get(SESSION_KEY_POINTS_GRANTED, default="0"))
            request.session[SESSION_KEY_POINTS_GRANTED] = str(points_granted)
        return JsonResponse({"status": "ok", "pointsAdded": float(num_points), "pointsGranted": float(points_granted)})

rewards/templates/rewards/list.html
{% extends "base.html" %}

{% load vue_utils %}

{% block header_name %}
  Choose
  your Rewards
{% endblock header_name %}
{% block content %}
  <!-- Show redeemed and unredeemed points -->
  <div class="mt-4">
    <div
      id="points-status"
      {# pass root properties via the dataset #}
      data-points-available="{{ redeemable_points }}"
      data-claim-url="{% url 'rewards:claim' %}"
      >
      {# 'djangoSlots' can be addressed by name and used as content in Vue components #}
      <h4 class="text-center mb-5" data-django-slot="message">You've earned DjangoCon rewards!</h4>
      {# They can include template logic and may be teleported anywhere on the page #}
      <p class="text-muted p-3" data-django-slot="disclaimer">
        Welcome, {{ request.user }}. This app is for demonstration purposes only.
        Rewards are entirely fictitious and may not be redeemed.
      </p>
    </div>
  </div>
  <!-- List the available rewards -->
  <div class="row mt-4">
    {% for r in rewards %}
      <div class="col-12 col-sm-6 col-lg-4 gy-5">
        <div class="card text-white bg-primary">
          <div class="card-header d-flex justify-content-between gap-2">
            <span class="h4 flex-grow">{{ r.name }}</span>
            <span class="h5">{{ r.point_value }}<small>pts</small></span>
          </div>
          <div class="card-body">
            <p>{{ r.description }}</p>
            <div class="reward-claim text-center"
                 data-reward-id="{{ r.id }}"
                 data-points="{{ r.point_value }}"></div>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock content %}
{% block inline_javascript %}
  <script type="module" crossorigin src="{% vue_bundle_url 'reward' %}"></script>
  {# 'provide" strings which can 'injected' throughout the Vue app, including from within a pinia store #}
  {% url 'rewards:bonus' as addPointsUrl %} {% vue_provide 'addPointsUrl' addPointsUrl %}
{% endblock inline_javascript %}